[project]
name = "black-scholes-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib==3.10.5",
    "polars==1.32.3",
    "requests>=2.32.5",
    "scipy==1.16.1",
    "seaborn==0.13.2",
]
