name: Code Formatting Check

on:
  push:
    branches: [ main, develop, fix-read-me ]
  pull_request:
    branches: [ main, develop ]

jobs:
  black-formatting:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check code formatting with Black
      uses: psf/black@stable
      with:
        options: "--check --diff"
        src: "."
        version: "~= 24.0"